title: Mai Le
logo: /assets/img/logo.jpg
description: Experienced Analyst with a demonstrated history of working in the banking and transportation industry. Skilled in Microsoft Office, Tableau, and various programming languages. And, currently expanding my skillset as a graduate Business Analytics student at Temple University
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
