title: <p align="center"> Mai Le </p>

logo: "/img/logo.jpg?raw=true"

description:
  <p align="center">
  <a href="https://tuprd-my.sharepoint.com/:b:/r/personal/tuq42303_temple_edu/Documents/Resume_Mai_Jan_2023_1.pdf?csf=1&web=1&e=2jivpg">Resume</a> |
  <a href="https://www.linkedin.com/in/maip-le/">LinkedIn</a> |
  <a href="https://public.tableau.com/app/profile/mai.phuong.le">Tableau</a> |
  <a href="https://github.com/maiphle">GitHub</a>
  </p>
  
  <p align="justify">
  Experienced analyst with a demonstrated history of working in the banking and transportation industry. Currently, looking to expand my skills beyond the classroom with professional experience. 
  
  I have a Bachelor of Business Administration in Global Supply Chain Management and Investment Finance from Rider University and am working on obtaining a Master of Science in Business Analytics at Temple University. 
  <br><br>

  </p>
  
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
